spring.application.name=eventos-api
spring.config.import=optional:file:.env[.properties],optional:file:apps/api/.env[.properties]
spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE:event_manager_pos}
app.security.bcrypt.custo=${BCRYPT_COST:8}
